name: Publish docker image JITStreamer-2.0

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: how does this look
        run: echo $github.repository
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/macleykun/jitstreamer-2.0:latest
          platforms: linux/arm64/v8,linux/amd64 #,linux/arm/v7,linux/386
