name: Publish docker image JITStreamer-2.0

on:
  push:
    branches:
      - 'main'
#    paths:
#      - '**.sh'
#      - 'Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert to lowercase
        id: convert2lowercase
        run: INPUT=${{ env.GITHUB_REPOSITORY }}; echo "GITHUB_REPOSITORY_LOWERCASE=${INPUT,,}">>${GITHUB_OUTPUT} 
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{steps.convert2lowercase.outputs.GITHUB_REPOSITORY_LOWERCASE}}:latest
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8
